import react from "@vitejs/plugin-react-swc";
import fs from "fs";
import path from "path";
import { UserConfigExport, defineConfig, loadEnv } from "vite";

const currentEnv = loadEnv(process.env.NODE_ENV, process.cwd());

export default defineConfig(({ command }) => {
  const config: UserConfigExport = {
    plugins: [react()],
  };

  if (command === "serve") {
    // command value is "serve" during "dev" (in the cli vite, "vite dev", and
    // "vite serve" are aliases), and "build" when building for production ("vite
    // build"). https://vitejs.dev/config/#conditional-config
    config.server = {
      host: currentEnv.VITE_WARP_HOST,
      https: {
        // these files are generated by running the above shell script
        key: fs.readFileSync(path.resolve(__dirname, "./.cert/server.key")),
        cert: fs.readFileSync(path.resolve(__dirname, "./.cert/server.crt")),
      },
      port: 3100,
    };
  }

  return config;
});
